=== sudonhim/cohen-db/schema/canon-file.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "canon-file.json",
    "title": "CanonFile",
    "description": "A collection of canonical material tied to a particular time, place, or release",
    "properties": {
        "user": {
            "type": "string",
            "description": "The username that owns the document and may edit it."
        },
        "version": {
            "type": "integer",
            "description": "The iteration of the document. Every edit increases this by one."
        },
        "title": {
            "type": "string",
            "description": "The string to use when showing this item in menus and links."
        },
        "kind": {
            "type": "string",
            "enum": ["group", "song", "live", "album", "tour", "interview", "other", "symbol","theme"],
            "description": "The category that this item belongs to."
        },
        "metadata": {
            "$ref": "metadata.json"
        },
        "content": {
            "$ref": "content.json"
        },
        "annotations": {
            "$ref": "annotations.json"
        },
        "children": {
            "type": "array",
            "description": "A list of child document IDs. E.g. if this document is an album, the children are songs. The IDs here are relative - the path part is omitted.",
            "items": {
                "type": "string"
            },
            "minItems": 1
        }
    },
    "required": ["user", "version", "title", "kind", "annotations"],
    "additionalProperties": false
  }

=== sudonhim/cohen-db/db/themes/politics-and-tribes.json
{
  "title": "Politics and Tribes",
  "kind": "group",
  "user": "sudonhim",
  "version": 1,
  "annotations": [],
  "children": [
    "theme.america",
    "theme.blacks-and-jews",
    "theme.capitalism-and-communism",
    "theme.church",
    "theme.enlightenment-and-liberalism",
    "theme.left-and-right",
    "theme.jewish-identity",
    "theme.nazis-and-jews"
  ]
}

=== sudonhim/cohen-db/db/miscellaneous.json
{
  "user": "sudonhim",
  "version": 0,
  "title": "Miscellaneous",
  "kind": "group",
  "annotations": [],
  "children": [
    "other.1966_01_01_from_the_original_selected_poems_19561968",
    "other.1974_12_31_the_best_of_leonard_cohen_some_notes_on_the_songs",
    "other.1980_11_01_the_song_of_leonard_cohen",
    "other.1985_05_17_night_magic",
    "other.2001_02_27_the_song_of_leonard_cohen_portrait_of_a_poet_a_friendship_and_a_film"
  ]
}

=== sudonhim/cohen-db/db/themes/buildings_and_transport.json
{
  "title": "Buildings and Transport",
  "kind": "group",
  "user": "sudonhim",
  "version": 1,
  "annotations": [],
  "children": [
    "theme.bridge",
    "theme.house_bed_door_window_and_kitchen",
    "theme.road",
    "theme.ships_and_planes",
    "theme.temple",
    "theme.trains_and_stations"
  ]
}

=== sudonhim/cohen-db/db/themes/politics_and_tribes.json
{
  "title": "Politics and Tribes",
  "kind": "group",
  "user": "sudonhim",
  "version": 1,
  "annotations": [],
  "children": [
    "theme.america",
    "theme.blacks_and_jews",
    "theme.capitalism_and_communism",
    "theme.church",
    "theme.enlightenment_and_liberalism",
    "theme.left_and_right",
    "theme.jewish_identity",
    "theme.nazis_and_jews"
  ]
}

=== sudonhim/cohen-db/db/songs/popular_problems/did_i_ever_love_you.json
{
  "title": "Did I Ever Love You",
  "content": {
    "content": {
      "text": [
        [
          "Did I ever love you",
          "Did I ever need you",
          "Did I ever fight you",
          "Did I ever want to"
        ],
        [
          "Did I ever leave you",
          "Was I ever able",
          "Or are we still leaning",
          "Across the old table"
        ],
        [
          "Was it ever settled",
          "Was it ever over",
          "And is it still raining",
          "Back in November"
        ],
        [
          "The lemon trees blossom",
          "The almond trees whither",
          "Was I ever someone",
          "Who could love you forever"
        ],
        [
          "Did I ever love you",
          "Does it really matter",
          "Did I ever fight you",
          "You donâ€™t need to answer"
        ],
        [
          "Did I ever leave you",
          "Was I ever able",
          "And are we still leaning",
          "Across the old table"
        ]
      ]
    }
  },
  "kind": "song",
  "annotations": [
    {
      "anchor": "p3.l3",
      "annotations": [
        {
          "user": "symbols bot",
          "content": [
            {
              "kind": "docref",
              "docRef": "symbol.rain"
            }
          ],
          "id": "1"
        }
      ],
      "newAnchor": "11"
    },
    {
      "anchor": "p4.l1",
      "annotations": [
        {
          "user": "symbols bot",
          "content": [
            {
              "kind": "docref",
              "docRef": "symbol.tree"
            }
          ],
          "id": "1"
        }
      ],
      "newAnchor": "13"
    }
  ],
  "user": "sudonhim",
  "version": 0
}

=== sudonhim/cohen-db/db/themes.json
{
  "title": "Themes",
  "kind": "group",
  "user": "sudonhim",
  "version": 1,
  "annotations": [],
  "children": [
    "group.activities",
    "group.body",
    "group.buildings-and-transport",
    "group.creatures-and-plants",
    "group.geography",
    "group.items",
    "group.life-and-feeling",
    "group.nature",
    "group.people-and-relationships",
    "group.philosophy",
    "group.politics-and-tribes",
    "group.sky-and-weather",
    "Substances"
  ]
}

=== sudonhim/cohen-db/db/themes/people-and-relationships.json
{
  "title": "People and Relationships",
  "kind": "group",
  "user": "sudonhim",
  "version": 1,
  "annotations": [],
  "children": [
    "theme.beggar",
    "theme.bride-and-bridegroom",
    "theme.doctor",
    "theme.god",
    "theme.gypsy",
    "theme.her-the-holy-spirit",
    "theme.hunter",
    "theme.jesus",
    "theme.killer",
    "theme.lovers-and-the-trinity",
    "theme.mothers-and-fathers",
    "theme.men-and-women",
    "theme.singer",
    "theme.soldier",
    "theme.stranger"
  ]
}

=== sudonhim/cohen-db/db/miscellaneous/1985_05_17_night_magic.json
{
  "user": "sudonhim",
  "version": 0,
  "title": "Night Magic",
  "kind": "other",
  "annotations": [],
  "metadata": {
    "date": "1985-05-17"
  },
  "content": {
    "kind": "multipart",
    "content": [
      {
        "id": "variation_on_hunters_lullaby",
        "title": {
          "kind": "text",
          "tokens": [
            {
              "kind": "text",
              "text": "On "
            },
            {
              "kind": "reference",
              "reference": {
                "kind": "document",
                "documentId": "song.hunters_lullaby"
              }
            }
          ]
        },
        "fragments": [
          {
            "kind": "text",
            "id": "1",
            "tokens": [
              {
                "kind": "text",
                "text": "The song is sung by a female, and has a different ending:"
              }
            ]
          },
          {
            "kind": "lineBreak"
          },
          {
            "kind": "lineBreak"
          },
          {
            "kind": "text",
            "id": "2",
            "tokens": [
              {
                "kind": "text",
                "text": "And he's lost my lucky charm"
              }
            ]
          },
          {
            "kind": "lineBreak"
          },
          {
            "kind": "text",
            "id": "2",
            "tokens": [
              {
                "kind": "text",
                "text": "He's lost the guardian heart"
              }
            ]
          },
          {
            "kind": "lineBreak"
          },
          {
            "kind": "text",
            "id": "2",
            "tokens": [
              {
                "kind": "text",
                "text": "That keeps the hunter from the harm"
              }
            ]
          },
          {
            "kind": "lineBreak"
          },
          {
            "kind": "lineBreak"
          },
          {
            "kind": "text",
            "id": "2",
            "tokens": [
              {
                "kind": "text",
                "text": "There's a darkness in the thicket"
              }
            ]
          },
          {
            "kind": "lineBreak"
          },
          {
            "kind": "text",
            "id": "2",
            "tokens": [
              {
                "kind": "text",
                "text": "That was not there before"
              }
            ]
          },
          {
            "kind": "lineBreak"
          },
          {
            "kind": "text",
            "id": "2",
            "tokens": [
              {
                "kind": "text",
                "text": "And among the tangled undergrowth"
              }
            ]
          },
          {
            "kind": "lineBreak"
          },
          {
            "kind": "text",
            "id": "2",
            "tokens": [
              {
                "kind": "text",
                "text": "There is one tangle more"
              }
            ]
          },
          {
            "kind": "lineBreak"
          },
          {
            "kind": "text",
            "id": "2",
            "tokens": [
              {
                "kind": "text",
                "text": "Your father's gone a-hunting"
              }
            ]
          }
        ]
      }
    ]
  }
}
