=== SudoNhim/cohen-db/schema/canon-file.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "canon-file.json",
    "title": "CanonFile",
    "description": "A collection of canonical material tied to a particular time, place, or release",
    "properties": {
        "title": {
            "type": "string",
            "description": "The string to use when showing this item in menus and links."
        },
        "kind": {
            "type": "string",
            "enum": ["group", "song", "live", "album", "tour", "interview", "other"],
            "description": "The category that this item belongs to."
        },
        "metadata": {
            "$ref": "metadata.json"
        },
        "content": {
            "$ref": "content.json"
        },
        "annotations": {
            "$ref": "annotations.json"
        },
        "children": {
            "type": "array",
            "description": "A list of child document IDs. E.g. if this document is an album, the children are songs. The IDs here are relative - the path part is omitted.",
            "items": {
                "type": "string"
            },
            "minItems": 1
        }
    },
    "required": ["title", "kind"],
    "additionalProperties": false
  }

=== SudoNhim/cohen-db/db/songs/im_your_man/im_your_man.json
{
  "title": "I'm Your Man",
  "content": {
    "content": {
      "text": [
        [
          "If you want a lover",
          "I'll do anything you ask me to",
          "And if you want another kind of love",
          "I'll wear a mask for you",
          "If you want a partner, take my hand, or",
          "If you want to strike me down in anger",
          "Here I stand",
          "I'm your man"
        ],
        [
          "If you want a boxer",
          "I will step into the ring for you",
          "And if you want a doctor",
          "I'll examine every inch of you",
          "If you want a driver, climb inside",
          "Or if you want to take me for a ride",
          "You know you can",
          "I'm your man"
        ],
        [
          "Ah, the moon's too bright",
          "The chain's too tight",
          "The beast won't go to sleep",
          "I've been running through these promises to you",
          "That I made and I could not keep",
          "Ah, but a man never got a woman back",
          "Not by begging on his knees",
          "Or I'd crawl to you baby and I'd fall at your feet",
          "And I'd howl at your beauty like a dog in heat",
          "And I'd claw at your heart, and I'd tear at your sheet",
          "I'd say please (please)",
          "I'm your man"
        ],
        [
          "And if you've got to sleep a moment on the road",
          "I will steer for you",
          "And if you want to work the street alone",
          "I'll disappear for you",
          "If you want a father for your child",
          "Or only want to walk with me a while across the sand",
          "I'm your man"
        ],
        [
          "If you want a lover",
          "I'll do anything you ask me to",
          "And if you want another kind of love",
          "I'll wear a mask for you"
        ]
      ]
    }
  },
  "kind": "song",
  "annotations": [
    {
      "anchor": "p1.l1",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.lover"
        }
      ],
      "user": "sudonhim"
    },
    {
      "anchor": "p1.l8",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.man"
        }
      ],
      "user": "sudonhim"
    },
    {
      "anchor": "p2.l3",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.doctor"
        }
      ],
      "user": "sudonhim"
    },
    {
      "anchor": "p2.l8",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.man"
        }
      ],
      "user": "sudonhim"
    },
    {
      "anchor": "p3.l1",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.moon"
        }
      ],
      "user": "sudonhim"
    },
    {
      "anchor": "p3.l3",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.sleep"
        }
      ],
      "user": "sudonhim"
    },
    {
      "anchor": "p3.l6",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.man"
        }
      ],
      "user": "sudonhim"
    },
    {
      "anchor": "p3.l6",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.woman"
        }
      ],
      "user": "sudonhim"
    },
    {
      "anchor": "p3.l10",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.heart"
        }
      ],
      "user": "sudonhim"
    },
    {
      "anchor": "p3.l12",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.man"
        }
      ],
      "user": "sudonhim"
    },
    {
      "anchor": "p4.l1",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.road"
        }
      ],
      "user": "sudonhim"
    },
    {
      "anchor": "p4.l1",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.sleep"
        }
      ],
      "user": "sudonhim"
    },
    {
      "anchor": "p4.l5",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.father"
        }
      ],
      "user": "sudonhim"
    },
    {
      "anchor": "p4.l7",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.man"
        }
      ],
      "user": "sudonhim"
    },
    {
      "anchor": "p5.l1",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.lover"
        }
      ],
      "user": "sudonhim"
    }
  ]
}

=== SudoNhim/cohen-db/db/songs/popular_problems/a_street.json
{
  "title": "A Street",
  "content": {
    "content": {
      "text": [
        [
          "I used to be your favorite drunk",
          "Good for one more laugh",
          "Then we both ran out of luck",
          "Luck was all we ever had",
          "You put on a uniform",
          "To fight the Civil War",
          "You looked so good I didn't care",
          "What side you’re fighting for"
        ],
        [
          "It wasn't all that easy",
          "When you up and walked away",
          "But I’ll save that little story",
          "For another rainy day",
          "I know the burden’s heavy",
          "As you wheel it through the night",
          "Some people say it’s empty",
          "But that don’t mean it’s light"
        ],
        [
          "You left me with the dishes",
          "And a baby in the bath",
          "You’re tight with the militias",
          "You wear their camouflage",
          "You always said we’re equal",
          "So let me march with you",
          "Just an extra in the sequel",
          "To the old red white and blue"
        ],
        [
          "Baby don’t ignore me",
          "We were smokers, we were friends",
          "Forget that tired story",
          "Of betrayal and revenge",
          "I see the ghost of culture",
          "With numbers on his wrist",
          "Salute some new conclusion",
          "That all of us have missed"
        ],
        [
          "I cried for you this morning",
          "And I’ll cry for you again",
          "But I’m not in charge of sorrow",
          "So please don’t ask me when",
          "There may be wine and roses",
          "And magnums of champagne",
          "But we’ll never know",
          "We'll never, ever be that drunk again"
        ],
        [
          "Okay",
          "The party’s over",
          "But I've landed on my feet",
          "And I’m standing here on this corner",
          "Where there used to be a street"
        ],
        [
          "The party’s over",
          "But I've landed on my feet",
          "I'll be standing on this corner",
          "Where there used to be a street"
        ],
        [
          "So let's drink to when its over",
          "And let's drink to when we met",
          "I'll be standing on this corner",
          "Where there used to be a street"
        ]
      ]
    }
  },
  "kind": "song",
  "annotations": [
    {
      "anchor": "p2.l4",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.day"
        }
      ],
      "user": "sudonhim"
    },
    {
      "anchor": "p2.l6",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.night"
        }
      ],
      "user": "sudonhim"
    },
    {
      "anchor": "p2.l8",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.light"
        }
      ],
      "user": "sudonhim"
    },
    {
      "anchor": "p3.l8",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.blue"
        }
      ],
      "user": "sudonhim"
    },
    {
      "anchor": "p3.l8",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.white"
        }
      ],
      "user": "sudonhim"
    },
    {
      "anchor": "p5.l5",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.rose"
        }
      ],
      "user": "sudonhim"
    }
  ]
}

=== SudoNhim/cohen-db/db/interviews/1992_11_24_interview_1992_from_a_cd_by_sony_music_the_future_radio_special.json
{
  "title": "1992-11-24 - Interview 1992 (from a CD by Sony Music \"The Future Radio Special\")",
  "metadata": {
    "date": "1992-11-24"
  },
  "content": {
    "content": [
      {
        "kind": "note",
        "reference": "song.always",
        "content": {
          "text": [
            "Well, there is an introduction, that kind of patter that used to be popular in the songs of the twenties and the thirties where the guy would set up the song in some way and this really is the chorus. Although, it became the song and people don't do the patter anymore, don't do that kind of set-up for it. But, there is one, it's very charming. I have a couple of improvised lines in there. I wouldn't have kept the track if it didn't have such exuberance. A number of the musicians told me it was among the happiest sessions they'd ever played. It was a good party."
          ]
        }
      }
    ]
  },
  "kind": "interview",
  "annotations": []
}

=== SudoNhim/cohen-db/db/songs/new_skin_for_the_old_ceremony/lover_lover_lover.json
{
  "title": "Lover, Lover, Lover",
  "content": {
    "content": {
      "text": [
        [
          "I asked my father,",
          "I said, \"father change my name.\"",
          "The one I'm using now it's covered up",
          "With fear and filth and cowardice and shame."
        ],
        [
          "Yes and lover, lover, lover, lover, lover, lover, lover come back to me,",
          "Yes and lover, lover, lover, lover, lover, lover, lover come back to me."
        ],
        [
          "He said, \"i locked you in this body,",
          "I meant it as a kind of trial.",
          "You can use it for a weapon,",
          "Or to make some woman smile.\""
        ],
        [
          "Yes and lover, lover, lover, lover, lover, lover, lover come back to me,",
          "Yes and lover, lover, lover, lover, lover, lover, lover come back to me."
        ],
        [
          "\"then let me start again,\" i cried,",
          "\"please let me start again,",
          "I want a face that's fair this time,",
          "I want a spirit that is calm.\""
        ],
        [
          "Yes and lover, lover, lover, lover, lover, lover, lover come back to me,",
          "Yes and lover, lover, lover, lover, lover, lover, lover come back to me."
        ],
        [
          "\"i never never turned aside,\" he said,",
          "\"i never walked away.",
          "It was you who built the temple,",
          "It was you who covered up my face.\""
        ],
        [
          "Yes and lover, lover, lover, lover, lover, lover, lover come back to me,",
          "Yes and lover, lover, lover, lover, lover, lover, lover come back to me."
        ],
        [
          "And may the spirit of this song,",
          "May it rise up pure and free.",
          "May it be a shield for you,",
          "A shield against the enemy."
        ],
        [
          "Yes and lover, lover, lover, lover, lover, lover, lover come back to me,",
          "Yes and lover, lover, lover, lover, lover, lover, lover come back to me."
        ],
        [
          "Yes and lover, lover, lover, lover, lover, lover, lover come back to me,",
          "Yes and lover, lover, lover, lover, lover, lover, lover come back to me."
        ]
      ]
    }
  },
  "kind": "song",
  "annotations": [
    {
      "anchor": "p11.l2",
      "tokens": [
        {
          "text": "In summary this song is a dialogue between God and the Jewish people. The Jew cries out \"God, why have you abandoned me? How have you allowed us to fall into such a wretched condition? Give us a fresh start, let us escape it!\". And God replies \"It was you who forgot me, I never left you. I have given everything that you need.\""
        }
      ]
    },
    {
      "anchor": "p2.l1",
      "tokens": [
        {
          "text": "LC is borrowing a technique from the 13th century Persian poet Rumi, who famously referred to god as his \"lover\". Rumi is credited in the album sleeve."
        }
      ]
    },
    {
      "anchor": "p3.l3",
      "tokens": [
        {
          "text": "This is commonly interpreted as a moral test - to choose love (make a woman smile) over violence (use it as a weapon). This fits with the pacifist currents of the 70s in the US, but its probable that the correct interpretation is much darker. Aligning with the fifth verse, the spirit of this song is to succeed \"against the enemy\". The rather than a choice then, these two lines become the most important things you can do with your god-given body; to fight, and to reproduce. This makes a lot more sense under the circumstances in which the song was written."
        }
      ]
    },
    {
      "anchor": "p5.l3",
      "tokens": [
        {
          "text": "An Israeli comments: \"...the new face - is the new way of relating to Jewish culture, to being a Jew in new times when there is finally a state which didnâ€™t exist before, the state which needs protection. Old stereotypes about Jews unable to defend themselves must be destroyed.\""
        }
      ]
    },
    {
      "anchor": "p9",
      "tokens": [
        {
          "text": "The overall spirit of the song - written for Israeli toops in the Yom Kippur War, it is for strengthening Jewish identity in the face of adversity and moral ambiguity. LC does claim that the song is for \"both sides\", and indeed it is true for any people in this struggle."
        }
      ]
    }
  ]
}

=== SudoNhim/cohen-db/db/songs/death_of_a_ladies_man/true_love_leaves_no_traces.json
{
  "title": "True Love Leaves No Traces",
  "content": {
    "content": {
      "text": [
        [
          "As the mist leaves no scar ",
          "On the dark green hill ",
          "So my body leaves no scar ",
          "On you and never will ",
          "Through windows in the dark ",
          "The children come, the children go ",
          "Like arrows with no targets ",
          "Like shackles made of snow "
        ],
        [
          "True love leaves no traces ",
          "If you and I are one ",
          "It's lost in our embraces ",
          "Like stars against the sun "
        ],
        [
          "As a falling leaf may rest ",
          "A moment on the air ",
          "So your head upon my breast ",
          "So my hand upon your hair "
        ],
        [
          "And many nights endure ",
          "Without a moon or star ",
          "So we will endure ",
          "When one is gone and far "
        ],
        [
          "True love leaves no traces ",
          "If you and I are one ",
          "It's lost in our embraces ",
          "Like stars against the sun"
        ]
      ]
    }
  },
  "kind": "song",
  "annotations": [
    {
      "anchor": "p0.l1",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.green"
        }
      ]
    },
    {
      "anchor": "p0.l1",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.dark"
        }
      ]
    },
    {
      "anchor": "p0.l4",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.window"
        }
      ]
    },
    {
      "anchor": "p0.l4",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.dark"
        }
      ]
    },
    {
      "anchor": "p0.l7",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.snow"
        }
      ]
    },
    {
      "anchor": "p1.l3",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.sun"
        }
      ]
    },
    {
      "anchor": "p1.l3",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.star"
        }
      ]
    },
    {
      "anchor": "p2.l3",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.hair"
        }
      ]
    },
    {
      "anchor": "p3.l0",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.night"
        }
      ]
    },
    {
      "anchor": "p3.l1",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.moon"
        }
      ]
    },
    {
      "anchor": "p3.l1",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.star"
        }
      ]
    },
    {
      "anchor": "p4.l3",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.sun"
        }
      ]
    },
    {
      "anchor": "p4.l3",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.star"
        }
      ]
    }
  ]
}

=== SudoNhim/cohen-db/db/interviews/2001_10_01_optimum_french_magazine.json
{
  "title": "2001-10-01 - Optimum - French magazine",
  "metadata": {
    "date": "2001-10-01"
  },
  "content": {
    "content": [
      {
        "kind": "note",
        "reference": "song.by_the_rivers_dark",
        "content": {
          "text": [
            "This song reports the peregrinations of a character in Babylon. He's part of it, then flees it, comes back to it. He belongs to the City of depravities while he knows there's a Jerusalem somewhere, even if he doesn't figure what's going on there. It's like our thoughts. Our brain is a receptacle for thoughts just as we are for Love. One doesn't really know what's arising in us the next moment. But our nature drives us to think we master these streams, while we master them no more than the location we're born in. We spend too much time thinking we're able to deny, disown our roots and our condition. This story is reflected in the character, except the fact he finally really understood where he comes from.. Even if an Eden exist, he does come from Babylon and has to face this, what will surely enable him to enjoy more the idea of a distant place, necessarily better."
          ]
        }
      }
    ]
  },
  "kind": "interview",
  "annotations": [
    {
      "anchor": "s1.p1",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.master"
        }
      ]
    }
  ]
}

=== SudoNhim/cohen-db/db/songs/various_positions/night_comes_on.json
{
  "title": "Night Comes On",
  "content": {
    "content": {
      "text": [
        [
          "I went down to the place where I knew she lay waiting",
          "Under the marble and the snow",
          "I said, Mother I'm frightened, the thunder and the lightning",
          "I'll never come through this alone",
          "She said, I'll be with you, my shawl wrapped around you",
          "My hand on your head when you go",
          "And the night came on, it was very calm"
        ],
        [
          "I wanted the night to go on and on",
          "But she said, go back, go back to the world",
          "We were fighting in Egypt when they signed this agreement",
          "That nobody else had to die",
          "There was this terrible sound, my father went down",
          "With a terrible wound in his side",
          "He said, try to go on, take my books, take my gun",
          "Remember, my son, how they lied",
          "And the night comes on, it's very calm",
          "I'd like to pretend that my father was wrong",
          "But you don't want to lie, not to the young"
        ],
        [
          "We were locked in this kitchen, I took to religion",
          "And I wondered how long she would stay",
          "I needed so much to have nothing to touch",
          "I've always been greedy that way",
          "But my son and my daughter climbed out of the water",
          "Crying, Papa, you promised to play",
          "And they lead me away to the great surprise",
          "It's Papa, don't peek, Papa, cover your eyes",
          "And they hide, they hide in the world"
        ],
        [
          "Now I look for her always, I'm lost in this calling",
          "I'm tied to the threads of some prayer",
          "Saying when will she summon me, when will she come to me",
          "What must I do to prepare?",
          "When she bends to my longing like a willow, like a fountain",
          "She stands in the luminous air",
          "And the night comes on, it's very calm",
          "I lie in her arms and says when I'm gone",
          "I'll be yours, yours for a song"
        ],
        [
          "Now the crickets are singing, the vesper bells ringing",
          "The cat's curled asleep in his chair",
          "I'll go down to Bill's Bar, I can make it that far",
          "And I'll see if my friends are still there",
          "Yes, and here's to the few, who forgive what you do",
          "And the fewer who don't even care",
          "And the night comes on, it's very calm",
          "I want to cross over, I want to go home",
          "But she says, Go back, go back to the world"
        ]
      ]
    }
  },
  "kind": "song",
  "annotations": [
    {
      "anchor": "p1.l2",
      "tokens": [
        {
          "text": "The temple and the snow form a sort of binary - those whose spiritual attachments are elevated and affirmed in the public square are in the temple, those who are exiled from it must make their home in the snow. Here LC locates the nurturing mother figure as being beneath both.",
          "kind": "text"
        }
      ],
      "user": "sudonhim"
    },
    {
      "anchor": "p2.l1",
      "tokens": [
        {
          "text": "The night is a time of comfort but also of illusion, as we are shielded from the world. In daytime we wrestle with reality, often in struggle and suffering, but our vision is clearer.",
          "kind": "text"
        }
      ],
      "user": "sudonhim"
    },
    {
      "anchor": "p2.l3",
      "tokens": [
        {
          "text": "This is the ceasefire agreement signed in the Yom Kippur war, which didn't last the night.",
          "kind": "text"
        }
      ],
      "user": "sudonhim"
    },
    {
      "anchor": "p1.l2",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.snow"
        }
      ],
      "user": "symbols bot"
    },
    {
      "anchor": "p1.l3",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.mother"
        }
      ],
      "user": "symbols bot"
    },
    {
      "anchor": "p1.l7",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.night"
        }
      ],
      "user": "symbols bot"
    },
    {
      "anchor": "p2.l1",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.night"
        }
      ],
      "user": "symbols bot"
    },
    {
      "anchor": "p2.l5",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.father"
        }
      ],
      "user": "symbols bot"
    },
    {
      "anchor": "p2.l8",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.son"
        }
      ],
      "user": "symbols bot"
    },
    {
      "anchor": "p2.l9",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.night"
        }
      ],
      "user": "symbols bot"
    },
    {
      "anchor": "p2.l10",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.father"
        }
      ],
      "user": "symbols bot"
    },
    {
      "anchor": "p3.l1",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.kitchen"
        }
      ],
      "user": "symbols bot"
    },
    {
      "anchor": "p3.l5",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.water"
        }
      ],
      "user": "symbols bot"
    },
    {
      "anchor": "p3.l5",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.daughter"
        }
      ],
      "user": "symbols bot"
    },
    {
      "anchor": "p3.l5",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.son"
        }
      ],
      "user": "symbols bot"
    },
    {
      "anchor": "p4.l7",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.night"
        }
      ],
      "user": "symbols bot"
    },
    {
      "anchor": "p5.l7",
      "tokens": [
        {
          "kind": "docref",
          "docRef": "symbol.night"
        }
      ],
      "user": "symbols bot"
    }
  ]
}

=== SudoNhim/cohen-db/db/performances/unmatched_variation/1974_09_18_birmingham.json
{
  "title": "1974-09-18 - Birmingham",
  "metadata": {
    "date": "1974-09-18"
  },
  "content": {
    "content": [
      {
        "kind": "variation",
        "reference": "db/songs/songs_of_love_and_hate/joan_of_arc",
        "content": {
          "text": [
            "Modified Verses",
            [
              "Who are you ?, she sternly spoke",
              "To the voice beneath the smoke",
              " And saying this she climbed inside",
              "To be his one, to be his virgin bride"
            ]
          ]
        }
      },
      {
        "kind": "prologue",
        "reference": "db/songs/songs_from_a_room/seems_so_long_ago_nancy",
        "content": {
          "text": [
            "I'd like to sing a song for a most beautiful blonde woman who died in 1961, in Montreal."
          ]
        }
      }
    ]
  },
  "kind": "live"
}
