=== sudonhim/cohen-db/schema/canon-file.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "canon-file.json",
    "title": "CanonFile",
    "description": "A collection of canonical material tied to a particular time, place, or release",
    "properties": {
        "user": {
            "type": "string",
            "description": "The username that owns the document and may edit it."
        },
        "version": {
            "type": "integer",
            "description": "The iteration of the document. Every edit increases this by one."
        },
        "title": {
            "type": "string",
            "description": "The string to use when showing this item in menus and links."
        },
        "kind": {
            "type": "string",
            "enum": ["group", "song", "live", "album", "tour", "interview", "other", "symbol","theme"],
            "description": "The category that this item belongs to."
        },
        "metadata": {
            "$ref": "metadata.json"
        },
        "content": {
            "$ref": "content.json"
        },
        "annotations": {
            "$ref": "annotations.json"
        },
        "children": {
            "type": "array",
            "description": "A list of child document IDs. E.g. if this document is an album, the children are songs. The IDs here are relative - the path part is omitted.",
            "items": {
                "type": "string"
            },
            "minItems": 1
        }
    },
    "required": ["user", "version", "title", "kind", "annotations"],
    "additionalProperties": false
  }

=== sudonhim/cohen-db/db/themes/people_and_relationships.json
{
  "title": "People and Relationships",
  "kind": "group",
  "user": "sudonhim",
  "version": 1,
  "annotations": [],
  "children": [
    "theme.beggar",
    "theme.bride_and_bridegroom",
    "theme.doctor",
    "theme.god",
    "theme.gypsy",
    "theme.her_the_holy_spirit",
    "theme.hunter",
    "theme.jesus",
    "theme.killer",
    "theme.lovers_and_the_trinity",
    "theme.mothers_and_fathers",
    "theme.men_and_women",
    "theme.singer",
    "theme.soldier",
    "theme.stranger"
  ]
}

=== sudonhim/cohen-db/db/themes/buildings-and-transport.json
{
  "title": "Buildings and Transport",
  "kind": "group",
  "user": "sudonhim",
  "version": 1,
  "annotations": [],
  "children": [
    "theme.bridge",
    "theme.house-bed-door-window-and-kitchen",
    "theme.road",
    "theme.ships-and-planes",
    "theme.temple",
    "theme.trains-and-stations"
  ]
}
